# Generated by Django 4.1.7 on 2023-03-19 20:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('root_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequencia', models.CharField(max_length=200)),
                ('avali', models.CharField(max_length=200)),
                ('risk', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Grupo personalizado',
                'verbose_name_plural': 'Grupos personalizados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
