# Generated by Django 4.1.7 on 2023-03-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_module', '0002_riskclass_customgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='modules',
            field=models.ManyToManyField(blank=True, limit_choices_to={'company': models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root_module.company')}, to='root_module.module'),
        ),
    ]
