# Generated by Django 4.1.7 on 2023-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_module', '0004_alter_users_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='modules',
            field=models.ManyToManyField(blank=True, to='root_module.module'),
        ),
    ]
