# Generated by Django 4.1.7 on 2023-03-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('company_id', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('group_type', models.CharField(max_length=100)),
                ('exit_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('quantity_stock', models.IntegerField()),
                ('storage', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('quantity_use', models.IntegerField()),
                ('minimum_quantity_stock', models.IntegerField()),
                ('Effect_Consequence_of_failure', models.IntegerField(default=0)),
                ('potential_existing_risk', models.CharField(default='UNDEFINED', max_length=100)),
                ('repairable', models.BooleanField(default=False)),
                ('strategy_when_fails', models.CharField(default='UNDEFINED', max_length=100)),
                ('Highest_criticality_of_assets', models.IntegerField(default=0)),
                ('failure_frequency', models.CharField(default='UNDEFINED', max_length=100)),
                ('cost_operation', models.FloatField(default=0)),
                ('volume_production', models.FloatField(default=0)),
                ('health_security', models.IntegerField(default=0)),
                ('environment', models.IntegerField(default=0)),
                ('lead_time_new', models.IntegerField(default=0)),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('modification_date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_module.stock')),
            ],
        ),
    ]
