# Generated by Django 4.1.7 on 2023-03-20 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('company_id', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('group_type', models.CharField(max_length=100)),
                ('exit_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('quantity_stock', models.IntegerField()),
                ('storage', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('quantity_use', models.IntegerField()),
                ('minimum_quantity_stock', models.IntegerField()),
                ('Effect_Consequence_of_failure', models.IntegerField(default=0)),
                ('potential_existing_risk', models.CharField(default='UNDEFINED', max_length=100)),
                ('repairable', models.BooleanField(default=False)),
                ('strategy_when_fails', models.CharField(default='UNDEFINED', max_length=100)),
                ('Highest_criticality_of_assets', models.IntegerField(default=0)),
                ('failure_frequency', models.CharField(default='UNDEFINED', max_length=100)),
                ('cost_operation', models.FloatField(default=0)),
                ('volume_production', models.FloatField(default=0)),
                ('health_security', models.IntegerField(default=0)),
                ('environment', models.IntegerField(default=0)),
                ('lead_time_new', models.IntegerField(default=0)),
                ('datatime', models.DateTimeField(blank=True, editable=False)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical stock',
                'verbose_name_plural': 'historical stocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
