# Generated by Django 4.1.7 on 2023-03-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_module', '0002_historicalstock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('codigo', 'company_id')},
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
