# Generated by Django 4.1.7 on 2023-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_module', '0003_alter_stock_unique_together_delete_stockhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
